name: haduong
favicon: null
layout_spectrum: 0.2888972358778119
typography_spectrum: 0.014762082369998097
title: Ha Duong - Personal Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-68403451-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7032307456247509
  lightness: 0.8801848276052624
  saturation: 0.592358973575756
  rhythmicContrast: 0.18736408138647676
purpose: []
